### ISSUE TITLE
Styling issue with twitter trends

### ISSUE THREAD

**Issue by tsriram** [tsriram/twitter-web-night-mode#11]
When you're on a page that isn't the home page the trends section looks a little weird.

Reported by Edwin on Chrome Web Store.

Screenshot - http://prnt.sc/cn4bs9

**Comment by LauraNK** [comment]
If you don't mind waiting a day or two, I'd be happy to take this on.

**Comment by tsriram** [comment]
@LauraNK sure :+1:

**Comment by tsriram** [comment]
Closed by #14
