### ISSUE TITLE
Theme selector

### ISSUE THREAD

**Issue by tsriram** [tsriram/twitter-web-night-mode#13]
Able to select a color theme from options. 
Asked by Shahin Jacob Ourian here - https://twitter.com/ShahinOurian/status/780084307524067329

**Comment by LauraNK** [comment]
I actually found your extension when I went looking for a dark theme for Twitter. I'd be more than happy to design the dark theme, but am less confident in creating the theme selector. Would you be willing to consider them 2 separate issues?

**Comment by tsriram** [comment]
@LauraNK yeah! How exactly do you want to split this? If you prefer, you make take up #12 first to get more familiarity with the code.

**Comment by LauraNK** [comment]
I could create the theme if someone else can create the ability to switch between the two. However if you don't mind me taking a bit of time with it, I'm sure I can manage both. 
Sure, I can tackle #12!

**Comment by tsriram** [comment]
Great. Sure, it can take some time :)

**Comment by LauraNK** [comment]
Looks like I'll have to pass this on to someone else, I likely wouldn't be able to get to it for at least a week or two.

**Comment by tsriram** [comment]
No problem, @LauraNK. I'm also kinda busy with work of late and I'll try to get started with this soon.

**Comment by nickkaczmarek** [comment]
@LauraNK @tsriram any chance of this happening?

**Comment by tsriram** [comment]
@Nickkaczmarek unfortunately not anytime soon :(
