### ISSUE TITLE
Dark grey font on dark background is very hard to read

### ISSUE THREAD

**Issue by LauraNK** [tsriram/twitter-web-night-mode#17]
There is a dark grey text color that appears in a variety of places that is very difficult to read against the dark blue background.
Example: http://i.imgur.com/wwzalF4.png

Seen in:
- Profile descriptions during search results
- In the "change" trends window
- Usernames and some news descriptions in Moments capsules

I'm happy to submit a PR.

**Comment by tsriram** [comment]
Should have been fixed by #18
