### ISSUE TITLE
Livestream Page needs fixing

### ISSUE THREAD

**Issue by ohitsmerenz** [tsriram/twitter-web-night-mode#19]
![image](https://cloud.githubusercontent.com/assets/22673690/19179114/94aeca64-8c8c-11e6-80ab-ccb9caf5c6da.png)

I don't know if you guys have access to this page, but this still needs styling. 
- Links not readable (depends on theme color)
- Main screen container needs fixing
- Text box still on light mode

**Comment by tsriram** [comment]
@ohitsmerenz what theme color are you using? I tried with a few colors and not able to see this bug.

**Comment by ohitsmerenz** [comment]
@tsriram I'm using dark grey theme color. It's a custom color from the color palette.
