### ISSUE TITLE
Night mode breaks as soon as I go to any twitter page other than the homepage.

### ISSUE THREAD

**Issue by KMShinkiro** [tsriram/twitter-web-night-mode#2]
Only https://twitter.com/ has night mode working. Pages like: https://twitter.com/?lang=en, any account page, any settings page and viewing a specific tweet all do not have the night mode working.

**Comment by ghost** [comment]
I tried to edit the code but the whole extension didn't work. This regex should work though: https:\/\/twitter.com\/.*

**Comment by tsriram** [comment]
@KMShinkiro, @2zqa - I have updated the extension to work for language pages like https://twitter.com/?lang=??
Need more time to make it work for all pages as the CSS classes used are different in different pages. Hoping to get some time for this soon.

**Comment by tsriram** [comment]
@KMShinkiro @2zqa closing this now. Please reopen if you still see this issue.
