### ISSUE TITLE
Moments page issues

### ISSUE THREAD

**Issue by ohitsmerenz** [tsriram/twitter-web-night-mode#20]
![image](https://cloud.githubusercontent.com/assets/22673690/19179202/91ce68c6-8c8d-11e6-9e79-0eaccc8d4997.png)

Moments container needs border radius
Scores on Games are not visible

**Comment by tsriram** [comment]
@ohitsmerenz looks like twitter itself doesn't have border radius for Moments container. Have just added the dark theme to container so the text should have some breathing space.

**Comment by tsriram** [comment]
Guess it's fixed. Feel free to reopen if it's not.
