### ISSUE TITLE
Theme Color clashing with night mode colors

### ISSUE THREAD

**Issue by ohitsmerenz** [tsriram/twitter-web-night-mode#23]
![image](https://cloud.githubusercontent.com/assets/22673690/19180424/40dbdaa6-8c98-11e6-935b-c212d6638275.png)

Maybe there's a way to force control theme colors on dark theme to just be blue. Some colors are not visible or doesn't go well with the dark theme

**Comment by tsriram** [comment]
This seems quite complex than expected. Quite a lot of styles defined as user styles in an internal style sheet. Guess I won't be able to override them in my CSS. Might have to play around with it using JS. Will get back to this.
