### ISSUE TITLE
That loader.

### ISSUE THREAD

**Issue by ohitsmerenz** [tsriram/twitter-web-night-mode#24]
![image](https://cloud.githubusercontent.com/assets/22673690/19180577/7872a908-8c99-11e6-835c-44c52fa89923.png)

Don't know if we could do something about this, but leaving this thing here.

**Comment by tsriram** [comment]
Ah, it's using this [image](https://abs.twimg.com/a/1475913038/img/t1/spinner-rosetta-blue-26x26.gif) which seems to have white border around it (you can try changing the background color). Don't think I can fix it now.
