### ISSUE TITLE
background colour becomes white after window resize

### ISSUE THREAD

**Issue by toxzykplayer** [tsriram/twitter-web-night-mode#27]
I'm using Chrome.
I noticed the issue when I had twitter open on my other screen which is smaller than my main screen.
The background will only be dark when the browser window is large enough to display the "who to follow" module on the right side, else it will be white.'

![dark](https://cloud.githubusercontent.com/assets/23056192/19689592/26dbb092-9ace-11e6-8463-b9c7b3055399.png)
![light](https://cloud.githubusercontent.com/assets/23056192/19689595/28ed8efa-9ace-11e6-9d3f-9eaa45034559.png)

**Comment by rowpsmo1859** [comment]
^ Pardon the noise. Was cleaning up a commit :smile:

**Comment by tsriram** [comment]
No problem @JeremyBellows. Will publish an update to Chrome store with this fix soon. Thanks again!

**Comment by rowpsmo1859** [comment]
:+1: 

I forgot to remove `three-col` from the logged-out selector.

**Comment by tsriram** [comment]
@JeremyBellows I'll push it in. Thanks!

**Comment by jtanigawa** [comment]
I have this issue on Firefox as well

**Comment by tsriram** [comment]
@jtanigawa yup, haven't published the fix to Firefox web store yet as the validation for it was failing with some error in manifest file. Will do it in a couple of days.

**Comment by nickkaczmarek** [comment]
@tsriram I'm assuming we can close this now?

**Comment by tsriram** [comment]
@Nickkaczmarek yeah, closing it now. Feel free to do so :)
