### ISSUE TITLE
my background in night mod does not changed

### ISSUE THREAD

**Issue by destrat18** [tsriram/twitter-web-night-mode#3]
after i change to night mod my background still stay white and do not become blue

**Comment by tsriram** [comment]
@destrat18 - are you using Chrome or Firefox? version? Can you please post a screenshot here?

**Comment by destrat18** [comment]
i using chrome:
Version 52.0.2743.116 m (64-bit)
in windows 10.
[image: Inline image 1]

**Comment by tsriram** [comment]
@destrat18 can't see the image? Can you upload again?

**Comment by destrat18** [comment]
hi. Sriram
i blocked images by my self. i do that because my internet in university is
fucking shit and blocked images to help twitter load faster :/.

**Comment by tsriram** [comment]
@destrat18 does it work fine now? Closing this issue...feel free to reopen if the problem persists.
