### ISSUE TITLE
Extra dark mode

### ISSUE THREAD

**Issue by tsriram** [tsriram/twitter-web-night-mode#30]
Ref - https://twitter.com/tsriram/status/817988224677187588

**Comment by tsriram** [comment]
If you happen to need this before the update lands in web stores, you can get the crx from here - https://drive.google.com/file/d/0B2l_YbxCHaWjYW9pQVVIbWlFWFU/view - and install.

**Comment by nickkaczmarek** [comment]
Is this still necessary to keep open?
