### ISSUE TITLE
Update Firefox store

### ISSUE THREAD

**Issue by Osahashi** [tsriram/twitter-web-night-mode#33]
Your Firefox app didn't update on the Firefox store: Version 0.0.6 Last Updated: October 11, 2016
You did say on Twitter it will be fixed, but it didn't. https://twitter.com/tsriram/status/820100289382457344

**Comment by tsriram** [comment]
Hey @Daisenki, sorry for the delay. Had submitted the new version to Firefox store this morning and waiting for their review & approval. It should be there soon!

**Comment by tsriram** [comment]
@Daisenki it's live now 😁

**Comment by Daisenki** [comment]
Hey Tsriram, please update the store, it is still the 0.0.10, no update to the 0.0.11 by now.
