### ISSUE TITLE
broken in 4k

### ISSUE THREAD

**Issue by Osahashi** [tsriram/twitter-web-night-mode#35]
Thanks for updating the Firefox store, I was hopping it fix the issue at my Twitter, but it didn't. I use a 4K display with native  3840x2160. Please look at the screenshot. :/

It only happens on the trend page.

![snip_20170122102702](https://cloud.githubusercontent.com/assets/22057956/22181485/ed9d256c-e08d-11e6-859d-5fbfceb1de6c.jpg)

**Comment by tsriram** [comment]
Ha, that looks bad. I don't have a monitor with this kind of resolution. Will try to figure out a way to fix this soon. Please bear with this for sometime.

**Comment by Osahashi** [comment]
If you need any information from me let me know it. It only happens at the trend page, so there must be any different. The bug is at window mode, full window and Firefox at fullscreen mode. I'm not exactlly sure what kind of bug it is, because it also happens on my second monitor with a 1920x1080 resolution when I move the tab. I can send you the debug info from my trend page in Firefox if you want it. 

I can deal with the bug, it's not that bad, so take your time, don't stress yourself. :)

**Comment by tsriram** [comment]
Cool. This is enough for me to debug I guess. Will ping you if I need something.

**Comment by Osahashi** [comment]
#40 same issue

**Comment by Osahashi** [comment]
Thanks tsriram, issue fixed with version 0.0.10 for me! :)
