### ISSUE TITLE
White background on quote tweets in Messages

### ISSUE THREAD

**Issue by bstrand** [tsriram/twitter-web-night-mode#39]
In DMs, quote tweets are shown with white text on a white background, ergo are illegible. Text is present, just not visible. Other messages are rendered as expected, and quote tweets in the standard timeline appear with the same dark background as standard tweets.

![screenshot 2017-02-06 18 16 04](https://cloud.githubusercontent.com/assets/188060/22675632/aec97074-ec9b-11e6-8dfe-fe64d27a782f.png)

**Comment by NjnaGrimsdottir** [comment]
Same problem here.... uninstalled over this flaw.

**Comment by tsriram** [comment]
@bstrand @JamieAzure sorry guys. Have been really busy. Finding time for it this weekend. Bear with this for a day more.
