### ISSUE TITLE
Why do you need access to history ?

### ISSUE THREAD

**Issue by CorentinMic** [tsriram/twitter-web-night-mode#4]
Why do you need access to history ?

**Comment by tsriram** [comment]
I do not need access to history. When I ask for permission to access tabs, Chrome Web Store tells the users that the extension needs access to history.

Here's the list of permission the extension needs and their purpose:
1. `https://twitter.com` - to inject the style sheet
2. `tabs` - whenever a new tab is opened and a page is loaded, extension checks if it is twitter.com
3. `storage` - to store whether the night mode is turned on or not
