### ISSUE TITLE
Trends need night mode

### ISSUE THREAD

**Issue by ghost** [tsriram/twitter-web-night-mode#40]
![screenshot_1](https://cloud.githubusercontent.com/assets/8940336/22949294/a3c8aeec-f2f9-11e6-9b9b-6e6bb53733a6.png)

**Comment by Osahashi** [comment]
#35 same issue

**Comment by Osahashi** [comment]
@TFSgamerPT it's fixed (for me/my issue) with the new version 0.0.10, please update the addon and check it.^^

**Comment by ghost** [comment]
For me it's still the same

**Comment by Osahashi** [comment]
Maybe the next version will fix it for all, look at: 
https://github.com/tsriram/twitter-web-night-mode/pull/46

**Comment by nickkaczmarek** [comment]
Has anyone had any problems with my update for #46?

**Comment by Osahashi** [comment]
@Nickkaczmarek how can we use your "update" as normal user with a normal firefox with the addon from the app store?

**Comment by nickkaczmarek** [comment]
@Daisenki you would have to follow the instructions on how to build the extension in the readme and then lookup how to load local firefox extensions. I don't have the ability to update the packages in the Chrome store or the Firefox store.

**Comment by nickkaczmarek** [comment]
Did the most recent update fix this or are you guys still waiting on firefox? @TFSgamerPT @Daisenki

**Comment by Osahashi** [comment]
I'm on 0.0.13, the issue is fixed for me, my ticket is already closed. :)

**Comment by ghost** [comment]
Now the issue is fixed, thanks 👍
