### ISSUE TITLE
Night mode for Moments Page Title Links

### ISSUE THREAD

**Issue by nickkaczmarek** [tsriram/twitter-web-night-mode#42]
Currently the theme works well with everything except for the title links in the heros for Moments. The links are too dark, but it appears changing '.MomentCapsuleSummary-title' handles the coloring well enough.

Current:
![current](https://cloud.githubusercontent.com/assets/9044401/23966185/783f5d98-0988-11e7-8976-9fd64c598cb3.PNG)

Suggested:
![suggested](https://cloud.githubusercontent.com/assets/9044401/23966184/7838cf64-0988-11e7-8d69-c61027057bfa.PNG)

I can create a PR to do this, but @tsriram you might be able to perform the updated quicker. Thanks.

**Comment by tsriram** [comment]
@Nickkaczmarek feel free to send a PR. Will update it in a day.

**Comment by tsriram** [comment]
@Nickkaczmarek have just published a new version on Chrome / Firefox stores and it should be available soon. Thanks for your contribution :)
