### ISSUE TITLE
Twitter Pole result colour change?

### ISSUE THREAD

**Issue by AdrianKoshka** [tsriram/twitter-web-night-mode#47]
I noticed the pole results (specifically the colour of the percentage bar) makes it a tad hard to read. Do you think the colour could be changed to something more sensible (or perhaps the colour of the font)?

![pole](http://i.imgur.com/xebbmE6.png)

**Comment by tsriram** [comment]
@AdrianKoshka absolutely! I'd like the background to be changed. Pushing in a fix today. Expect the update latest by tomorrow.

**Comment by AdrianKoshka** [comment]
I don't know if this was on purpose or not, but I (personally) don't think it solves the issue.

![nobar](http://imgur.com/tB9ZH5D.png)

**Comment by tsriram** [comment]
Oops, that wasn't intended. My bad, I missed checking the styles of ongoing polls. Will fix it soon. Could you check if polls that have ended display good?

**Comment by tsriram** [comment]
Well, even the ongoing polls look good to me. Can you confirm which version are you on?

**Comment by AdrianKoshka** [comment]
Can't confirm because haven't seen any polls in my feed lately, but I'm on version `0.0.11`
