### ISSUE TITLE
Update Firefox store version

### ISSUE THREAD

**Issue by Osahashi** [tsriram/twitter-web-night-mode#52]
Hey Tsriram, please update the store, it is still the 0.0.10, no update to the 0.0.11 by now. 

And can you please make a update with the hotfix from Nickkaczmarek? - https://github.com/tsriram/twitter-web-night-mode/pull/46 because the issue https://github.com/tsriram/twitter-web-night-mode/issues/40 to fix the problem for all users, it should be no big deal :)

**Comment by tsriram** [comment]
Have published v0.0.12 with minor fix in DM on both Chrome & Firefox stores and they should be available soon. Sorry for being quite lazy :frowning_face:

**Comment by tsriram** [comment]
Hey @Daisenki, that version didn't go through the Firefox store review process since they wanted some disclosure text about Google Analytics. Anyway I've removed GA as I'm not really using it to see the usage stats. New version 0.0.13 is submitted for review and should be available soon, hopefully.

**Comment by Osahashi** [comment]
Thanks :)
