### ISSUE TITLE
Lighter blue for links and #hashtags

### ISSUE THREAD

**Issue by tuckercollin** [tsriram/twitter-web-night-mode#61]
Could we brighten the links and hashtags? Its currently #0000CC, but I think #006DCC looks better. Thanks
![dark twitter links](https://cloud.githubusercontent.com/assets/7198991/25688284/67db2a5e-3043-11e7-8fe3-d0ae7ea07a29.png)
![dark twitter links 2](https://cloud.githubusercontent.com/assets/7198991/25688287/6a0a69d4-3043-11e7-920e-a969ec93a7ee.png)
![dark twitter links 3](https://cloud.githubusercontent.com/assets/7198991/25688291/6bbacf58-3043-11e7-8287-91133cb740e4.png)

**Comment by tsriram** [comment]
We don't use that blue (#0000CC) anywhere in the plugin. I guess it's coming from the twitter theme you'd have selected. Can you try changing the theme and see if it's still present?

**Comment by tuckercollin** [comment]
Okay, I looked into it, and there was a theme that was causing the color
issue. I closed the ticket, thanks.
