### ISSUE TITLE
New DM button to be coloured grey

### ISSUE THREAD

**Issue by araghunde** [tsriram/twitter-web-night-mode#62]
It seems like Twitter has recently introduced DM buttons that match what they look like in iOS and Android apps, but the colour of the button is blue while it should be gray (unless hovered over I assume)
![screenshot from 2017-05-23 15-00-50](https://cloud.githubusercontent.com/assets/3707802/26355476/268a4464-3fc9-11e7-81e8-7624aa79621e.png)

**Comment by tsriram** [comment]
@araghunde thanks for reporting. Have published a fix in `v0.0.16` now. Would be great if you could check and confirm.

**Comment by araghunde** [comment]
@tsriram yeah, thanks, that was fast! :smile: 
The button is no longer blue by default but now it doesn't change colour when hovered over, unless you are on an profile page. I took a couple screenshots for easier understanding:

When you hover over the DM button on an account's profile page (with their profile colour):
![twttr-hover-dm1](https://cloud.githubusercontent.com/assets/3707802/26414567/da1391ac-40af-11e7-93f9-29ec9f4e0af2.png)
When you hover over the DM button on your own Timeline (no colour, should be couloured as the reply button):
![twttr-hover-dm2](https://cloud.githubusercontent.com/assets/3707802/26414569/da338b6a-40af-11e7-8a34-72bf6d4181bc.png)

**Comment by tsriram** [comment]
Oh yeah, good catch! Looks like the color of other icons changes (RT icon to green & heart icon to red) too on hover when you're on a profile page. I think I'd probably let it behave this way for now.
