### ISSUE TITLE
Private message colors

### ISSUE THREAD

**Issue by PhantomKuze** [tsriram/twitter-web-night-mode#64]
Suddenly, the colors around the test of the person you speak changed suddenly, the black is not blank like the text, hard to read. 

![image](https://user-images.githubusercontent.com/29414371/27105789-299c330a-5091-11e7-8744-0ad145f25702.png)

**Comment by Valsisttv** [comment]
I can confirm this is also happening to me.

I either have to select the recieved message or disable the extension so I can read it.

**Comment by TheSaxyOne** [comment]
It just started for me yesterday as well.

**Comment by nickkaczmarek** [comment]
.DirectMessage--received .DirectMessage-text {
    background-color: #e6ecf0; 
    color: #14171a;

seems to be the culprit.

**Comment by PhantomKuze** [comment]
can we fix it by ourselves ?

**Comment by tsriram** [comment]
Ah, that's bad. I'm quite sure it worked earlier. Wonder if there's any change in twitter's CSS classes. I'll push a fix in a few hours. Please bear with it till then :)

**Comment by tsriram** [comment]
@PhantomKuze @Valsis-sf @TheSaxyOne @Nickkaczmarek have published v0.0.17 (I need to come up with better version number!) with the fix and it should be available soon on Chrome web store. Firefox review takes a while though.

**Comment by tsriram** [comment]
Can one of you confirm if this is really fixed? Thanks!
