### ISSUE TITLE
a issue with night mode on twitter 

### ISSUE THREAD

**Issue by gamernation89** [tsriram/twitter-web-night-mode#66]
yesturday i was going to dm someone on twitter and then this happened and i tried to disable and enable it again and it still has the same issue... please fix this because i can not stand having the white background and i can't dm on twitter with night mode 
![screenshot 124](https://user-images.githubusercontent.com/19208617/27142525-4a086272-50f9-11e7-832f-104388152d74.png)

**Comment by tsriram** [comment]
@gamernation89 this looks the same as #64. I've pushed a fix in version 0.0.17 and it should be available soon.
