### ISSUE TITLE
Dark Mode not being applied

### ISSUE THREAD

**Issue by Valsisttv** [tsriram/twitter-web-night-mode#67]
Dark mode, even when enabled, doesn't display in the background of the page itself.
![chrome_2017-06-14_21-48-32](https://user-images.githubusercontent.com/8517446/27154030-80c20550-514b-11e7-91ec-79e4567a06e5.png)

**Comment by PhantomKuze** [comment]
Personally, i don't have this problem on Chrome and firefox, i only still have this problem in Firefox Dms though.

**Comment by nickkaczmarek** [comment]
.MomentsPage.MomentsGuidePage {
    /* background-color: #fff!important; */

@tsriram
