### ISSUE TITLE
Few minor color changes

### ISSUE THREAD

**Issue by daftxcunt** [tsriram/twitter-web-night-mode#69]
![untitled](https://user-images.githubusercontent.com/29507678/27254870-73888eaa-5357-11e7-9c6e-6b418dcadc7b.png)

Maybe make the these, highlighted by red, to white? Minor stuff but would help. thanks

![screenshot_6](https://user-images.githubusercontent.com/29507678/27254904-11a2d686-5358-11e7-9db7-70c39586075e.png)
also on moments tab

PS: I'm using Firefox

**Comment by nickkaczmarek** [comment]
Closing as per PR #70

**Comment by nickkaczmarek** [comment]
I should probably keep this open until the updated packages go out for the chrome and firefox stores.

**Comment by arnofirdaus** [comment]
![image](https://user-images.githubusercontent.com/15241621/45692742-bcf4bb80-bb85-11e8-8611-abe56b9c7c1a.png)
the comment box still highlight, when a tweeps make a thread.

**Comment by nickkaczmarek** [comment]
@arnofirdaus This library is no longer in use as Twitter has implemented dark mode on their own. I'm going to close this now.
