### ISSUE TITLE
.ThreadedConversation-moreReplies still has light bg

### ISSUE THREAD

**Issue by rasputn** [tsriram/twitter-web-night-mode#71]

**Comment by nickkaczmarek** [comment]
Can you provide a screenshot of the issue in question.

**Comment by rasputn** [comment]
Here you go
![capture](https://user-images.githubusercontent.com/8933010/28128336-41640c38-66e4-11e7-931f-abfa38b2c69d.PNG)

**Comment by tsriram** [comment]
Thanks for the screenshot. Will get the fix pushed in by weekend.

**Comment by tsriram** [comment]
Published v0.0.19 and it should be available soon.
