### ISSUE TITLE
Photos get cut off with dark Twitter enabled

### ISSUE THREAD

**Issue by iQuickPwnz** [tsriram/twitter-web-night-mode#74]
There is an issue with the extension at the moment where pictures on Twitter get cut off, as u can see in the following gyazo's.

On black Twitter the picture always gets cut off/cropped at the bottom. The bottom of the picture text is not transparent. It takes the place of where the picture should of been, and cropping the picture out as result.

On white Twitter u can see that the picture is not cut off/cropped out at the bottom. Also is the bottom where the text of the picture is transparent. How it should be.

But instead the black twitter is not transparent, making the bottom of the picture cropped out. This is for every picture on twitter right now with dark Twitter enabled.

I hope I have informed u enough about this bug/glitch and that u can fix it.

Thank you,
Kevin

The Tweet: https://twitter.com/DreamHackCSGO/status/888928773567021056

Black Twitter:
https://gyazo.com/d5526f6bfa117bc216306aa848fcb8e3            Original tweet picture
https://gyazo.com/7ca7d1ba672cb402bd633038764100d1         Picture with text over it, cropped out
https://gyazo.com/3afce8c389cd6008b7c174a394b78fd9            Text dissapear, however full picture not revealed

White Twitter:
https://gyazo.com/45b9f1f3be4df9de680f75af90ceb416            Original tweet picture
https://gyazo.com/57d3374b53bc76fd3cc773408f1ea106          Picture with text over it
https://gyazo.com/d9bbae3cdd64d2bfbd2fc09f928153bc          Text dissapear and full picture revealed

**Comment by tsriram** [comment]
@iQuickPwnz thanks for the bug report, good catch. Will hopefully find some time by this weekend to fix this.

**Comment by iQuickPwnz** [comment]
@tsriram Thanks for replying and making time this weekend to fix the bug. Will be looking forward to the bug fixed.

**Comment by tsriram** [comment]
@iQuickPwnz have just published v0.0.20 with a fix for this and it should be available soon (in an hour or so). Would be great if you could confirm if it worked :)

**Comment by jwin742** [comment]
I was also having this issue and the recent update has solved it for me

**Comment by iQuickPwnz** [comment]
@tsriram I have just checked, and it works perfectly. Thank you for pushing this update out. :)
