### ISSUE TITLE
Web Twitter has now a native night mode

### ISSUE THREAD

**Issue by Osahashi** [tsriram/twitter-web-night-mode#76]
Hi, 

maybe you didn't know it, but Twitter Web has now a native night mode. Everyone can activate it without any addon and it works without any issues at the layout.

You find it under your profile pic at the right corner, the last setting.

**Comment by tsriram** [comment]
Hey @Daisenki, yes, [I know](https://twitter.com/tsriram/status/895229637235585025) that there's an official version. But it's not been rolled out to all users - I don't have it yet. [As per a twitter dev](https://twitter.com/kpk/status/905637541524627458), it'll take about a couple of weeks for full roll out. Once I can be quite sure that it's available for everyone,  I'm planning to show a notification from the extension about the official night mode and ask users to uninstall (:cry:) the extension.

Thanks for letting me know anyway :smile:

**Comment by Osahashi** [comment]
Thank you for your great addon, I did use it a long time and really liked it! It was the first night mode addon for Twitter web on the Firefox store and you always care about bugfixes and updates. Thx for that! :)

**Comment by tsriram** [comment]
Ah, thanks for your kind words :)
