### ISSUE TITLE
button for Twitter Web - Night Mode not visible with Firefox 55.0.3

### ISSUE THREAD

**Issue by grahamperrin** [tsriram/twitter-web-night-mode#77]
<https://addons.mozilla.org/addon/twitter-web-night-mode/>

> … at the click of a button.

– and after installing the extension I do have night mode but I don't see (in the toolbar of Firefox) a button to disable the mode. 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% uname -v
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info firefox | grep -i version
Version        : 55.0.3_1,1
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

**Comment by grahamperrin** [comment]
Reloading the page did not workaround. 

## Workaround

- Quit Firefox

– on the next visit to the Twitter page, the button appears (in the location field).

**Comment by tsriram** [comment]
Ah, okay. Good that it worked. If you're not aware, twitter has launched the official version of night mode for web. https://twitter.com/TwitterSupport/status/905477696360112129
