### ISSUE TITLE
A problem with the dark mode

### ISSUE THREAD

**Issue by SnowyIssue** [tsriram/twitter-web-night-mode#79]
I have a bit of a problem with this dark mode. When you go to different profiles you don't get their selected color and some text blend to well with the dark background. please fix this :)

**Comment by nickkaczmarek** [comment]
@SnowyIssue As far as I'm aware, this extension is no longer in development as Twitter now supports native night mode. 

https://github.com/tsriram/twitter-web-night-mode#update-sep-25-2017---this-extension-is-retired-and-will-no-longer-be-supported-as-twitter-has-launched-official-night-mode-for-the-website-read-more

**Comment by tsriram** [comment]
Thanks @nickkaczmarek.

@SnowyIssue yeah, I don't intend to fix any issues as the official night mode is out and I think everyone will probably start using it. Ain't you using the official night mode yet?
