### ISSUE TITLE
Dark mode doesn't apply to DM text boxes, chat bubbles, buttons

### ISSUE THREAD

**Issue by MReschenberg** [tsriram/twitter-web-night-mode#80]
<img width="786" alt="screen shot 2018-06-25 at 3 35 21 pm" src="https://user-images.githubusercontent.com/14968521/41879215-7d8d0032-788d-11e8-8537-0db4d2ee8714.png">
<img width="813" alt="screen shot 2018-06-25 at 3 35 48 pm" src="https://user-images.githubusercontent.com/14968521/41879216-7da2a98c-788d-11e8-96d0-aec0a102e700.png">
See above. It also doesn't apply when selecting from the list of people to share a tweet with; font clashes and is difficult to read.

**Comment by nickkaczmarek** [comment]
@tsriram might know better, but my impression is that development on this has ceased as twitter now supports night mode natively.

**Comment by nickkaczmarek** [comment]
Closing this in reference to https://github.com/tsriram/twitter-web-night-mode#update-sep-25-2017---this-extension-is-retired-and-will-no-longer-be-supported-as-twitter-has-launched-official-night-mode-for-the-website-read-more
